Ft(newsletter subscribe): user can subscribe to our newsletter
PrinceNiyonshuti/ATLP-capstone-project pull request #24
Opened 2022-03-17 18:36 UTC by PrinceNiyonshuti

#### What does this PR do?

- Implements user subscribing and unsubscribing to our newsletter

#### Description of Task to be completed? 

**As a user** I should be able to subscribe to the newsletter and also i can unsubscribe from it 

users can be able to:
- subscribe to our newsletter

#### How should this be manually tested?

- Clone the repo

- checkout to branch ``ft-subscribe-To-Newsletter``

- pull the changes by running `git pull`

#### Any background context you want to provide?
N/A
#### What are the relevant Pivotal Tracker/Trello stories?

- [link to Trello Board](https://trello.com/c/awZbRvuE/41-subscribe-to-newsletter-014)

#### Screenshots (if appropriate)

** Validating Email Input**

![image](https://user-images.githubusercontent.com/46887030/158872433-96d0e7e8-e951-4e66-bb77-45a66cef4f36.png)

**New User Subscribing**

![image](https://user-images.githubusercontent.com/46887030/158872508-54c916f9-f63a-4da3-9cb4-d492de9d9224.png)

**Existing User Trying To Subscribe**

![image](https://user-images.githubusercontent.com/46887030/158872562-935e6233-3b45-4f34-b48b-60921501c79c.png)

#### Questions:

N/A

2022-03-17 22:30 UTC, harerajo approved these changes

2022-03-18 05:14 UTC, PatrickNiyogitare28 requested changes

2022-03-18 05:14 UTC, PatrickNiyogitare28 commented on js/auth.js
> +	// }
Remove the commented source codes

2022-03-18 05:14 UTC, PatrickNiyogitare28 commented on js/firebase.js
> +// const api = "https://atlp-backend-prince.herokuapp.com/api/v1/";
Remove that as well

2022-03-18 21:03 UTC, merged